### ISSUE TITLE
Visualizzazione della classifica

### ISSUE THREAD

**Issue by eutampieri** [eutampieri/sitoOII#7]
Secondo voi va bene il criterio attuale di visualizzazione della classifica (**in base alla scuola di appartenenza**) oppure devono essere mostrati **solo gli utenti iscritti** oppure solo **uno dei due** criteri deve essere soddisfatto?

**Comment by eutampieri** [comment]
Alcuni utenti non sono più nella nostra scuola mentre certi studenti non hanno l’account registrato all’Alberghetti

**Comment by eutampieri** [comment]
@eutampieri Ugo: Secondo me possiamo fare gli utenti iscritti al nostro sito Più altri che vogliamo tenere come riferimento, magari vogliamo mettere Matilde Kevin Ragazzini

**Comment by MyK00L** [comment]
altrimenti si può fare una drop-down-list dove uno può decidere chi vedere, del tipo
>iscritti
>studenti dell'Alberghetti
>tutti
e magari anche gente attiva se l'API del cms ce lo permette...
