### ISSUE TITLE
Registrazione

### ISSUE THREAD

**Issue by MyK00L** [eutampieri/sitoOII#9]
E se uno vollesse le notifiche sia da telegram che per e-mail?
(non penso proprio, ma almeno dovrebbe avere la possibilità...)

**Comment by eutampieri** [comment]
@MyK00L È già in cantiere (guarda la branch)

**Comment by MyK00L** [comment]
beh almeno adesso abbiamo un issue, io non ci metto le mani sulla registrazione dato che non so il php
